name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  csm_gate_foundation_view:
    path: ../

  csm_view: 
    git: 
      url: https://github.com/Cosmos-CSM/csm_view
      ref: org_refactor_break

  csm_client_core: 
    git: 
      url: https://github.com/Cosmos-CSM/csm_client
      ref: dart_fixes
      path: csm_client_core/


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
