<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<RootNamespace>CSM_Gate_Foundation_Core_Testing</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CSM.Security.Database.Core" Version="3.1.0" />
        <PackageReference Include="CSM.Security.Database.Testing" Version="3.0.0" />
        <PackageReference Include="CSM.Server.Core.Testing" Version="5.0.0-rc.7" />
    </ItemGroup>

</Project>
